force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/PromotionName__c.field-meta.xml
<CustomField>
    <fullName>PromotionName__c</fullName>
    <label>Promotion Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRAFT</fullName>
                <default>true</default>
                <label>DRAFT</label>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PromotionFixtureFactory.cls
/**
 * @author: eduardo.bisso - dev-builder
 */
@isTest
public class PromotionFixtureFactory {

    public static Promotion__c createPromotion() {
        return  createPromotion ( 'Test' );
    }

    public static Promotion__c createPromotion(String name) {
        return  createPromotion ( newPromotion( name ) );
    }

    public static Promotion__c newPromotion(String name) {

        Date yesterday = Date.today().addDays(-1);        

        return new Promotion__c ( PromotionName__c = name
            , Status__c = 'ACTIVE'
            , StartDate__c = yesterday
            , DueDate__c = yesterday.addDays(30) ); 
    }

    public static Promotion__c newPromotion() {
        return newPromotion( 'Test' );
    }

    public static Promotion__c createPromotion(Promotion__c promotion) {

        insert promotion;
        return promotion;

    }

    public static Promotion__c fromJson (String payload) {
        return (Promotion__c) JSON.deserialize(payload, Promotion__c.class);
    }
    
    public static List<Promotion__c> fromJsonArray (String payload) {
        return (List<Promotion__c>) JSON.deserialize(payload, List<Promotion__c>.class);
    }


}