force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRAFT</fullName>
                <default>true</default>
                <label>DRAFT</label>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromotionalProduct__c/PromotionalProduct__c.object-meta.xml
<CustomObject>
    <label>Promotional Product</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotional Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionalProduct__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PromotionalProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Promotional Products</relationshipLabel>
    <relationshipName>PromotionalProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionalProduct__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promotional Products</relationshipLabel>
    <relationshipName>PromotionalProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PromotionalProductRepository.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public virtual class PromotionalProductRepository {

    virtual
    public List<PromotionalProduct__c> findAvailablePromotionsForProducts ( List<String> productIds ) {

        return [SELECT Discount__c                     
                    , Product__r.Id, Product__r.ProductCode
                    , Id 
                FROM PromotionalProduct__c
                WHERE Product__c IN :productIds
                    AND Promotion__r.StartDate__c <= TODAY 
                    AND Promotion__r.DueDate__c >= TODAY
                    AND Promotion__r.Status__c = 'ACTIVE'
                ORDER BY Promotion__r.CreatedDate, Promotion__c
         ];

    }


}