force-app/main/default/objects/PromotionalProduct__c/PromotionalProduct__c.object-meta.xml
<CustomObject>
    <label>Promotional Product</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotional Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionalProduct__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PromotionalProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Promotional Products</relationshipLabel>
    <relationshipName>PromotionalProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PromotionalProduct.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public class PromotionalProduct {
    
    public String productId;

    public String productCode;

    public Decimal discount;  

    public String promotionalProductId;
    
    public PromotionalProduct (Product2 product) {
        
        this.productId = product.Id;
        this.productCode = product.ProductCode;
        
    }

    public PromotionalProduct (Product2 product, Decimal discount) {
        
        this(product);
        this.discount = discount;
        
    }

    public PromotionalProduct (Product2 product, Decimal discount, String promotionalProductId) {
        
        this(product, discount);
        this.promotionalProductId = promotionalProductId;
        
    }

    public PromotionalProduct ( PromotionalProduct__c promotionalProduct ) {

        this (promotionalProduct.Product__r
            , promotionalProduct.Discount__c
            , promotionalProduct.Id );
    }

}