force-app/main/default/objects/PromotionalProduct__c/PromotionalProduct__c.object-meta.xml
<CustomObject>
    <label>Promotional Product</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotional Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionalProduct__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PromotionServiceTest.cls
/**
 * @author eduardo.bisso - dev-builder
 */
@isTest (isParallel=true)
public class PromotionServiceTest {

    @isTest
    public static void shouldReturnOldPromotion () {

        Map<String, SObject> records = PromotionalProductFixtureFactory.createIntegratedScenarioWithMultiplePromotions();

        Product2 product = (Product2) records.get('product');

        PromotionalProduct__c expected = (PromotionalProduct__c) records.get('promotionalProduct');

        PromotionService service = new PromotionService();

        Test.startTest();

        List<PromotionalProduct> promotionalProducts = service.findPromotionalProducts( new List<String> {
                                                                                                product.Id
                                                                                            } );
        
        Test.stopTest();
                                
        Assert.isFalse(promotionalProducts.isEmpty());

        Assert.areEqual( expected.Discount__c, promotionalProducts.get(0).discount);
        Assert.areEqual( expected.Id, promotionalProducts.get(0).promotionalProductId);
      

    }


}